AllCops:
  Excludes:
    - tmp/**
    - vendor/**
    - .git/**
    - ruby/**
    - log/**

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

ClassLength:
  Enabled: false

SignalException:
  # prefer raise to fail
  EnforcedStyle: only_raise

Documentation:
  # document classes
  Enabled: false

CollectionMethods:
  # don't prefer map to collect, reduce to inject, etc.
  Enabled: false

WordArray:
  # declare word arrays as word arrays
  Enabled: false

StringLiterals:
  # use single or double-quoted strings, as you please
  Enabled: false

Encoding:
  # no need to always specify encoding
  Enabled: false

ClassVars:
  # TODO: review, these are things like @@configs ||= {}
  Enabled: false

AlignParameters:
  # TODO: align to the left instead of to the indent
  Enabled: false

RescueModifier:
  # TODO: things like model = klass.constantize rescue nil
  Enabled: false

Void:
  # specs, ==
  Enabled: false

NumericLiterals:
  # We deal with money, so most aren't separated on 3-digit intervals.
  Enabled: false

Eval:
  Enabled: false

SymbolName:
  # we use const_defined?(:BUILD_STATUSES)
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Lambda:
  Enabled: false

AsciiComments:
  Enabled: false

RegexpLiteral:
  Enabled: false

MultilineBlockChain:
  Enabled: false

Blocks:
  Enabled: false

HandleExceptions:
  Enabled: false

ParameterLists:
  Enabled: false

FavorSprintf:
  Enabled: false
